### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by ShawnLYU** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#103]
Thanks for this great repo. However, when I tried to follow the [demo](https://github.com/tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#demo), I received this error:
```
Traceback (most recent call last):
  File "demo/picture_demo.py", line 18, in <module>
    from network.rtpose_vgg import get_model
ModuleNotFoundError: No module named 'network'
```
I was wondering is it necessary to append the path to ```sys.path``` in the script?

**Comment by ShawnLYU** [comment]
Solved.
The problem is that Python on my machine does not automatically add the current dir into the ```sys.path```. So the solution is to add it to ```PYTHONPATH```:
```
export PYTHONPATH="$PWD":$PYTHONPATH
```

**Comment by zharthur** [comment]
> Solved.
> The problem is that Python on my machine does not automatically add the current dir into the `sys.path`. So the solution is to add it to `PYTHONPATH`:
> 
> ```
> export PYTHONPATH="$PWD":$PYTHONPATH
> ```

Hello, I also met this issue, but I don't know how to add into sys.path. Could you tell me?
Thank you!
