### ISSUE TITLE
lib/datasets/coco_data is missing

### ISSUE THREAD

**Issue by yuzi56** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#104]
I can't find the folder 'coco_data' in lib/datasets, may be this folder is missing.

**Comment by tensorboy** [comment]
Hi @yuzi56,

It is deleted and sees the new data loader in `lib/datasets/datasets.py`, which can directly load `train2017` of the coco dataset.

**Comment by yuzi56** [comment]
However, when I run python evaluate/evaluation.py, it has some errors:
Traceback (most recent call last):
  File "evaluate/evaluation.py", line 3, in <module>
    from evaluate.coco_eval import run_eval
  File "/pytorch_Realtime_Multi-Person_Pose_Estimation-master/evaluate/coco_eval.py", line 12, in <module>
    from lib.datasets.coco_data.preprocessing import (inception_preprocess,
ModuleNotFoundError: No module named 'lib.datasets.coco_data'

**Comment by tensorboy** [comment]
Hi @yuzi56 I will try to fix the evaluation part then.

**Comment by tensorboy** [comment]
I added it back to './lib/datasets/'

**Comment by yuzi56** [comment]
Thanks for your help!
