### ISSUE TITLE
How to get the file like “person_keypoints_train2017.json” for my dataset?

### ISSUE THREAD

**Issue by IvyYZ** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#111]

**Comment by tensorboy** [comment]
You need to convert your dataset with the coco format such as https://github.com/waspinator/pycococreator/blob/d29534e36aad6c30d7e4dadd9f4f7b0e344a774c/pycococreatortools/pycococreatortools.py#L25

**Comment by saanvi03** [comment]
Can you please elaborate. I am able to generate keypoints on image but unable to save it in json file.
