### ISSUE TITLE
Where is  '_ckpt_epoch_150.ckpt' , in the validation code?

### ISSUE THREAD

**Issue by fuxiaoaaa** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#112]
Hello,
I've finished my training,then I want to run the validation code.But in the evaluation code, the "/data/rtpose/rtpose_lr01/0/_ckpt_epoch_150.ckpt" model is needed. Where should I find this '_ckpt_epoch_150.ckpt' file?

**Comment by anerisheth19** [comment]
> Hello,
> I've finished my training,then I want to run the validation code.But in the evaluation code, the "/data/rtpose/rtpose_lr01/0/_ckpt_epoch_150.ckpt" model is needed. Where should I find this '_ckpt_epoch_150.ckpt' file?

I have the same question. Can someone answer?

**Comment by tensorboy** [comment]
You can change it to the model you trained or the model downloaded from this repo.
