### ISSUE TITLE
get_multiplier() function

### ISSUE THREAD

**Issue by myOpenCV** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#113]
Hi,
   all:
   when I run the web_demo.py, I could not find the get_multiplier() function, could anyone tell me where is the function?
   thanks!

**Comment by veronikayurchuk** [comment]
I have the same issue :(

**Comment by myOpenCV** [comment]
> I have the same issue :(

so, I modified the demo with the picture_demo.py!
good luck!

**Comment by veronikayurchuk** [comment]
So I did :)

**Comment by Naruto-Zhao** [comment]
@myOpenCV I could not find the get_multiplier() function too.Could you tell me how to solve it?

**Comment by Naruto-Zhao** [comment]
> So I did :)
I have the same issue.Could you tell me how to solve this problem?

**Comment by myOpenCV** [comment]
> @myOpenCV I could not find the get_multiplier() function too.Could you tell me how to solve it?

I just modified the demo with the picture_demo.py!
