### ISSUE TITLE
no module named '_pafprocess'

### ISSUE THREAD

**Issue by wadeld123** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#119]
![TBB%5D~YJ$2 4P~$ M{)C](https://user-images.githubusercontent.com/26327939/67213011-da165080-f44f-11e9-8293-03a276f94682.png)

**Comment by rovesoul** [comment]
i have the same question

**Comment by gjm441** [comment]
cd lib/pafprocess; sh make.sh
