### ISSUE TITLE
How‘s CPM refinement working？

### ISSUE THREAD

**Issue by hufengshuo07** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#12]
Table 4 in papar mentioned that CPM refinement can provide more than 2.6% AP increase. Is it a post-processing method? Has it been added to the existed code?  Thanks for answer.

**Comment by tensorboy** [comment]
The model has 12 outputs, and 6 for paf and 6 for heatmap, You mean the refinement is 1->2->3->4->5->6 of heatmap and paf in the model.
