### ISSUE TITLE
A bug in demo/web_demo.py

### ISSUE THREAD

**Issue by jiang-du** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#120]
I tried to run `python demo/web_demo.py`. I am using pytorch 1.3 with python 3.7.4 at Anaconda3 on Ubuntu 18.04 system.
It reports:

```
  File "demo/web_demo.py", line 129
    break
    ^
SyntaxError: 'break' outside loop
```

I think there maybe something wrong with the loop. Were you meant to include the `lines 90~129` inside the looping `while True:` at `line 77`?

**Comment by Jichen66** [comment]
Hi, I also met the same problem. Have you solved that? Thanks in advance!

**Comment by jiang-du** [comment]
> Hi, I also met the same problem. Have you solved that? Thanks in advance!

Not yet. While I choose to run picture demo instead, and it works.

**Comment by jiang-du** [comment]
> Hi, I also met the same problem. Have you solved that? Thanks in advance!

I solved it. By reproducing the implementation in `picture_demo.py`, I modified the loop in `web_demo.py`, and it works on a camera.

```python
    while True:
        # Capture frame-by-frame
        ret, oriImg = video_capture.read()
        shape_dst = np.min(oriImg.shape[0:2])

        # Get results of original image
        with torch.no_grad():
            paf, heatmap, im_scale = get_outputs(oriImg, model,  'rtpose')
        from lib.utils.paf_to_pose import paf_to_pose_cpp
        from lib.config import cfg
        humans = paf_to_pose_cpp(heatmap, paf, cfg)
        out = draw_humans(oriImg, humans)
        
        # Display the resulting frame
        cv2.imshow('Video', out)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
```

**Comment by huyin92** [comment]
> > Hi, I also met the same problem. Have you solved that? Thanks in advance!
> 
> I solved it. By reproducing the implementation in `picture_demo.py`, I modified the loop in `web_demo.py`, and it works on a camera.
> 
> ```python
>     while True:
>         # Capture frame-by-frame
>         ret, oriImg = video_capture.read()
>         shape_dst = np.min(oriImg.shape[0:2])
> 
>         # Get results of original image
>         with torch.no_grad():
>             paf, heatmap, im_scale = get_outputs(oriImg, model,  'rtpose')
>         from lib.utils.paf_to_pose import paf_to_pose_cpp
>         from lib.config import cfg
>         humans = paf_to_pose_cpp(heatmap, paf, cfg)
>         out = draw_humans(oriImg, humans)
>         
>         # Display the resulting frame
>         cv2.imshow('Video', out)
> 
>         if cv2.waitKey(1) & 0xFF == ord('q'):
>             break
> ```

modify 'if' to 'while' is ok: " while cv2.waitKey(1) & 0xFF == ord('q'): "

**Comment by tensorboy** [comment]
Fixed the issue, updated code, thanks!
