### ISSUE TITLE
web_demo.py lack of get_multiplier function?

### ISSUE THREAD

**Issue by YuqingWu79** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#122]
![image](https://user-images.githubusercontent.com/31976855/67661861-2b1ccc00-f99d-11e9-8b4a-4cdf018201e0.png)
i can't find the function:get_multiplier, can somebody tell me how to deal with it?
![image](https://user-images.githubusercontent.com/31976855/67661980-746d1b80-f99d-11e9-9210-461d49d0a022.png)

**Comment by wsakobe** [comment]
Me too.. Have you fixed this bug?

**Comment by zhangzongyu00** [comment]
I have the same question. Have you fixed? 
How can I deal with it? 
Thanks!

**Comment by tensorboy** [comment]
Hi @wsakobe @zhangzongyu00 

It's in the file of `web_demo.py` now. :)
