### ISSUE TITLE
couldn't reproduce the same result

### ISSUE THREAD

**Issue by myOpenCV** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#123]
Hi，
    tensorboy:
    following your steps and the default parameters, I traind 75 epoches, but I could not get the results of the model you provided, So, whether you did some other operations？ @tensorboy 
    best wishes!

**Comment by tensorboy** [comment]
Sure, I'm back to debug it now, made a lot of changes before, I will finding what's the problem.
