### ISSUE TITLE
C++ inference

### ISSUE THREAD

**Issue by albertchristianto** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#125]
Hi @tensorboy, what a great repository.
I am new at C++ programming and know that paf computation is very slow in python. what did you do to improve the performance ? multi-thread or just simply convert it to c++?
best regards,
Albert Christianto

**Comment by tensorboy** [comment]
Hi @albertchristianto 
it simply converts it to c++.

**Comment by 121649982** [comment]
> Hi @tensorboy, what a great repository.
> I am new at C++ programming and know that paf computation is very slow in python. what did you do to improve the performance ? multi-thread or just simply convert it to c++?
> best regards,
> Albert Christianto


Have you converted it to c++? looking forward to your reply
