### ISSUE TITLE
SOLVED : Missing methods in common.py for get_face_box and get_upper_body_box

### ISSUE THREAD

**Issue by arduinepo** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#132]
Hi,
First, I than you very much for your good work :-) .
The methods get_face_box() and get_upper_body_box() calls several times the functions _include_parts() and _round(), which aren't defined anywhere ? or maybe have I missed something ?
I am also working on [get_face_box](https://github.com/Erkil1452/gaze360) to improve its results, which aren't good enough for my purpose (I use your network's outputs to infer a gaze estimation with gaze360, which needs face boxes to crop full images and obtain only single face images)
Thanks
Best

EDIT : found the functions in the tf-pose-estimation. Sorry for the post

**Comment by zeyger** [comment]
Add this to lib/utils/common.py:
 
```
import math
def _round(v):
    return int(round(v))


def _include_part(part_list, part_idx):
    for part in part_list:
        if part_idx == part.part_idx:
            return True, part
    return False, None
```
