### ISSUE TITLE
test without CUDA

### ISSUE THREAD

**Issue by IvonaTau** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#14]
Hi!

I was trying to run the Python demo `picture_demo.py` however I keep getting error:
`File "/usr/local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 51, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled`

Is it possible to run it without CUDA ? 

Thanks!

(I installed Pytorch from http://pytorch.org for OS X)

**Comment by tensorboy** [comment]
Yes, you just need to comment out "model.cuda()" and "Variable(....).cuda"

**Comment by IvonaTau** [comment]
Thanks ! Removing all instances of cuda() in the code solved the problem
