### ISSUE TITLE
Did the authour use the mask_miss and the mask_all when generate the heatmap and vecmap?

### ISSUE THREAD

**Issue by xiangweifeng** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#15]
And a I meet another problem. If the datasets have no  miss mask and all mask, then how I should deal with  miss mask and all mask. Let them all '1'?

**Comment by tensorboy** [comment]
mask_all is not used all the time. mask_miss is used for mask out unlabeled person. :)

**Comment by xiangweifeng** [comment]
Thanks a lot.
