### ISSUE TITLE
More instructions to train the model 

### ISSUE THREAD

**Issue by Bigwode** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#19]
Thanks for your work ! Your test model runs very well, but I have some troubles when I train the model in my dataset, So can you share your way to train the model or you can share your train codes for your convenient.Thanks a lot !!!

**Comment by Ai-is-light** [comment]
I want to the methods of  data-augmentation and data transform in the original paper's method. How did you resolve the data problems.@ @tensorboy @Bigwode Thanks

**Comment by tensorboy** [comment]
Try `train.py`
