### ISSUE TITLE
picture_demo.py line 304 missing a case, with correction attached

### ISSUE THREAD

**Issue by lordfjw** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#21]
I think it should be:
            if found == 1:
                j = subset_idx[0]
                if (subset[j][indexB] != partBs[i]):
                    subset[j][indexB] = partBs[i]
                    subset[j][-1] += 1
                    subset[j][-2] += candidate[partBs[i].astype(int), 2] + connection_all[k][i][2]
                if (subset[j][indexA] != partAs[i]):
                    subset[j][indexA] = partAs[i]
                    subset[j][-1] += 1
                    subset[j][-2] += candidate[partAs[i].astype(int), 2] + connection_all[k][i][2]

Otherwise, in some cases different subsets won't merge correctly. Thank you!

**Comment by lordfjw** [comment]
I am using this code for research and have met some problems. After debugging I find such an issue and manage to fix it. This is just a kind reminder. Thank you!

**Comment by am-khan** [comment]
Can you include the correct indentation?

**Comment by lordfjw** [comment]
Here you are:          
            if found == 1:
                j = subset_idx[0]
                if(subset[j][indexB] != partBs[i]):
                    subset[j][indexB] = partBs[i]
                    subset[j][-1] += 1
                    subset[j][-2] += candidate[partBs[i].astype(int), 2] + connection_all[k][i][2]
                if (subset[j][indexA] != partAs[i]):
                    subset[j][indexA] = partAs[i]
                    subset[j][-1] += 1
                    subset[j][-2] += candidate[partAs[i].astype(int), 2] + connection_all[k][i][2]

**Comment by lordfjw** [comment]
if found == 1:
                j = subset_idx[0]
                if(subset[j][indexB] != partBs[i]):
                    subset[j][indexB] = partBs[i]
                    subset[j][-1] += 1
                    subset[j][-2] += candidate[partBs[i].astype(int), 2] + connection_all[k][i][2]
                if (subset[j][indexA] != partAs[i]):
                    subset[j][indexA] = partAs[i]
                    subset[j][-1] += 1
                    subset[j][-2] += candidate[partAs[i].astype(int), 2] + connection_all[k][i][2]
