### ISSUE TITLE
training code does not work

### ISSUE THREAD

**Issue by zhixuany** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#22]
In function "train" of TODO-train_from_scratch.py, the line "target = target.cuda(async=True)" causes an error "AttributeError: 'dict' object has no attribute 'cuda'". How could I fix it?

**Comment by GAVANXU** [comment]
@zhixuany Did you solve this problem? I also encountered the same problem. What should I do?

**Comment by ybai62868** [comment]
@GAVANXU @zhixuany I meet the same question...  Can you tell me how to solve this problem.Thanks a lot.

**Comment by tensorboy** [comment]
Try `train.py`
