### ISSUE TITLE
Hungarian algorithm for part association

### ISSUE THREAD

**Issue by pavanteja295** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#23]
Hi,
   I read in the paper of part affinity that Hungarian algorithm is used for association of limbs when multiple contenders exist for a limb but in the code normal greedy association is done by eliminating the chances of multiple associations 
`if(i not in connection[:,3] and j not in connection[:,4]):`` Line 306 in picture_demo.py

Explanation in the paper is different.Any insights?

**Comment by tensorboy** [comment]
It is to make sure  joints_src[i] or joints_dst[j] haven't already been connected to other joints_dst or joints_src, right?

https://github.com/tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation/blob/master/network/post.py#L254

**Comment by pavanteja295** [comment]
The approach here is more greedy based . Hungarian algorithm gives us the analytical solution for the assignment problem. I can contribute for implementing this.

**Comment by tensorboy** [comment]
You are very very welcome to contribute, let me know if you need any help!
