### ISSUE TITLE
FPS Question on GPU Mode

### ISSUE THREAD

**Issue by timho102003** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#25]
Running thru ur web.demo code, the fps is about 1.2(Image size = 960x540).
Is there any way speed up the system?
Looking forward to your response!!!!!!

**Comment by still-wait** [comment]
@timho102003 Did you solve this problem, how to speed up the pytorch?

**Comment by tensorboy** [comment]
Maybe try a lighter backbone.

**Comment by lan2720** [comment]
@timho102003 What is the GPU you use? my fps is about 0.5 in 1080ti.
