### ISSUE TITLE
train from scratch----getData.sh 

### ISSUE THREAD

**Issue by FlyingRoastDuck** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#26]
It seems that http://msvocds.blob.core.windows.net/annotations-1-0-3/person_keypoints_trainval2014.zip in your shell script doesn't contain data files for training. Would you mind updating the script?
    By the way, I'm working on the training process of  Convolutional Pose Machines. Line 266 of TODO-train_from_scratch.py indicates that loss of the network is computed via pose's heatmap and person_keypoints_val2014.json contains the heatmap infomation. Is it proper for me to think this way? If it's right, how to judge the heatmap's radius for each keypoint?
    Thank you.

**Comment by tensorboy** [comment]
Try `train.py`
