### ISSUE TITLE
Which version of pytorch and opencv?

### ISSUE THREAD

**Issue by AndrewSoul** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#28]
Thanks for your work. I  want to ask that which version of pytorch and opencv did you use? Can I run the demo  on windows or ubuntu  by using pytorch-cpu?

**Comment by AndrewSoul** [comment]
Emm. I saw the code 'from torch import np' in web_demo.py .

**Comment by tommasogritti** [comment]
I guess you figured out already, but for other people reading this: it is PyTorch 3.1 and OpenCV 3.1 / 3.2.
You can install PyTorch for Cuda8.0 with: pip install http://download.pytorch.org/whl/cu80/torch-0.3.1-cp27-cp27mu-linux_x86_64.whl

**Comment by tensorboy** [comment]
It works on 0.4 now.
