### ISSUE TITLE
How to tell points from points?

### ISSUE THREAD

**Issue by xuehy** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#32]
Hello. I use the `picture_demo.py` to generate the pose coordinates for a person. The detected joint coordinates are stored in array `all_peaks`. However, how can I tell which point, for example, belongs to the arm, and which belongs to the leg?

**Comment by xuehy** [comment]
I have found the order the the pose coordinates.

**Comment by pinkfloyd06** [comment]
Hi @xuehy ,

How did you get the key points coordinates given an input image ?

Thank you
