### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by goberoi** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#34]
Thank you for sharing your code. Apologies if I missed it, but I don't see a license specified. Could you please let us know what license this is shared under, and if it can be used commercially?

**Comment by tensorboy** [comment]
Do whatever you want. :)

**Comment by goberoi** [comment]
@tensorboy thanks for your response. Can I request that you add a license to the repository? That will allow myself and other developers to confidently work with your code, resulting in your code being more widely used (and maybe more stars!).

For a commonly used, and generally permissive license, please consider the MIT license: https://choosealicense.com/licenses/mit

Alternatively, explore other license options from this excellent site: https://choosealicense.com

**Comment by tensorboy** [comment]
It is here now: https://github.com/tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation/blob/master/LICENSE

**Comment by goberoi** [comment]
Thank you!

**Comment by goberoi** [comment]
Hi there, happy to help, though I never did end up using this code, and therefore cannot say too many things. Still, feel free to drop me a note and we can take it from there. I'm my username at gmail.

**Comment by bloodymeli** [comment]
Hi,
 

It seems that the link:
https://github.com/tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation/blob/master/LICENSE

can you please release this repository with an APACHE license?
