### ISSUE TITLE
CPU mode

### ISSUE THREAD

**Issue by Sugarbank** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#4]
Hi is it possible to run in CPU mode only?

**Comment by tensorboy** [comment]
Yes, you can set it by "model.cpu()" and "Variable(numpy_image).cpu()"

Best,

**Comment by Sugarbank** [comment]
that worked thanks.If anyones interest processing time is about 30 seconds for 1 person in frame:)
