### ISSUE TITLE
Why picture_demo.py doesn't detect any key point from a given image ?

### ISSUE THREAD

**Issue by pinkfloyd06** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#41]
Hi @tensorboy ,

I find it strange that **picture_demo.py** doesn't detect any key point from the following image of size (320,240,3)

![v_diving_g08_c02_0001](https://user-images.githubusercontent.com/17967029/43602868-86a74930-9691-11e8-87a4-44af5e97812d.jpeg)

What is wrong ?

Thank you for your answer

**Comment by tensorboy** [comment]
I agree, the scale of the person is the problem for that work I think.

**Comment by pinkfloyd06** [comment]
I do agree, may be because the MS COCO dataset on which the network is trained doesn't contain small persons
