### ISSUE TITLE
Training model - COCO.json incomplete

### ISSUE THREAD

**Issue by miktoki** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#43]
The link to COCO.json https://www.dropbox.com/s/0sj2q24hipiiq5t/COCO.json?dl=0 provides an incomplete JSON file (it is abruptly cut off at line 311090)

JSON linter output:
```
Error: Parse error on line 311090:
...00, 391.000, 1.000],
-----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOF'
```

**Comment by tensorboy** [comment]
Hi, @miktoki, thanks for your information. 

What is the code you are using for the decoding of that COCO.json?

**Comment by miktoki** [comment]
@tensorboy 
I tried using both json and ujson with python3.6. 

If you look at the final lines of the JSON file, it is clear that it is incomplete (several missing brackets, and number of fields is different from the earlier objects):

```
		{
			"dataset": "COCO",
			"isValidation": 0.000,https://jsonlint.com/
			"img_paths": "train2014/COCO_train2014_000000015586.jpg",
			"img_width": 480.000,
			"img_height": 640.000,
			"objpos": [266.605,333.660],
			"image_id": 15586.000,
			"bbox": [53.210,38.830,426.790,589.660],
			"segment_area": 161299.833,
			"num_keypoints": 8.000,
			"joint_self": [
				[157.000,282.000,1.000],
				[209.000,227.000,1.000],
				[159.000,222.000,1.000],
				[363.000,245.000,1.000],
				[0.000,0.000,2.000],
				[0.000,0.000,2.000],
				[247.000,391.000,1.000],
```
The JSON linter output was just taken by pasting the content of the json file into an online linter (https://jsonlint.com/)

Do you mean the [genJSON.m](https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/blob/master/training/genJSON.m) file? I will take a look at it.

**Comment by tensorboy** [comment]
Thanks for sharing that online linter. :)

It is `genJSON.m` file. I'm not sure the reason, it is OK for me to do training.

Hope you can solve it.

**Comment by tensorboy** [comment]
My bad, I uploaded a wrong file, will update it soon.
