### ISSUE TITLE
Why heatmap doesn't sum to 1 ?

### ISSUE THREAD

**Issue by pinkfloyd06** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#44]
Hi  @tensorboy,

I'm wondering why heatmap doesn't sum to 1 since each pixel of heatmap represents the probability that a key point is encoded in that location.

Since we have 18 key points (each key point with its heatmap), where the highest value in a a given heatmap  is the probability of having that key point in that location. However when l sum a given heatmap, it doesn't sum  to 1, it exceeds drastically one. I get 450, 534.3 ...

Why ?
Am l missing something ?

Thank you for your answer

**Comment by tensorboy** [comment]
Hi, @pinkfloyd06 .

In the work of mask-rcnn, the heatmap constrained to 1, but the heatmap in this work didn't have this constrain. :)
