### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#45]
Excuse me,which version pytorch do you use for this project? @tensorboy

**Comment by tensorboy** [comment]
0.4

**Comment by MoonBunnyZZZ** [comment]
Thx.And you trained your model from scratch using the default paramater? @tensorboy

**Comment by tensorboy** [comment]
Yes, I didn't change parameters as I can remember.

**Comment by tensorboy** [comment]
Yeah, train_VGG.py will do it!

**Comment by MoonBunnyZZZ** [comment]
How to fix the demo error?
During testing picture_demo.py,I got this error.The model used is the downloaded one.
![screenshot from 2018-08-21 11-27-58](https://user-images.githubusercontent.com/30332524/44383054-f1a33200-a549-11e8-9770-caa2662f6066.png)

**Comment by MoonBunnyZZZ** [comment]
How to fix the demo error?Using train_VGG.py?
During testing picture_demo.py,I got this error.The model used is the downloaded one from your repo.
![screenshot from 2018-08-21 11-27-58](https://user-images.githubusercontent.com/30332524/44383208-7ee68680-a54a-11e8-964f-96e4de236888.png)
 @tensorboy

**Comment by tensorboy** [comment]
`model = torch.nn.DataParallel(model).cuda()` will do it, because the model trained by multi-gpu, it will have  a `module` prefix.

**Comment by wm901115nwpu** [comment]
Traceback (most recent call last):
  File "train_ShuffleNetV2.py", line 300, in <module>
    train_loss = train(train_data, model, optimizer, epoch)
  File "train_ShuffleNetV2.py", line 145, in train
    for i, (img, heatmap_target, heat_mask, paf_target, paf_mask) in enumerate(train_loader):
  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 189, in default_collate
    raise TypeError((error_msg.format(type(batch[0]))))
TypeError: batch must contain tensors, numbers, dicts or lists; found <class 'NoneType'>

**Comment by wm901115nwpu** [comment]
pytorch version 0.4.1

**Comment by tensorboy** [comment]
It caused by the data loader, could you please check if the path of the image/mask is right?

**Comment by wm901115nwpu** [comment]
python train_ShuffleNetV2.py --batch_size 160 --logdir log --json_path training/dataset/COCO/images/COCO.json --data_dir training/dataset/COCO/images/

run this, is it right?

**Comment by tensorboy** [comment]
It should be right. :)
