### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by wm901115nwpu** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#46]
python train_ShuffleNetV2.py --json_path training/dataset/COCO.json --data_dir training/dataset/COCO/images --mask_dir training/dataset/COCO

Loading dataset...
Traceback (most recent call last):
  File "train_ShuffleNetV2.py", line 266, in <module>
    shuffle=True, training=True, num_workers=16)
TypeError: get_loader() missing 1 required positional argument: 'params_transform'

**Comment by tensorboy** [comment]
This is because I pull the param_transform out to control the data augmentation. It is fixed now. :)
