### ISSUE TITLE
opencv error 

### ISSUE THREAD

**Issue by wm901115nwpu** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#48]
train dataset len: 121522
val dataset len: 4873
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
Traceback (most recent call last):
  File "train_ShuffleNetV2.py", line 300, in <module>
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
    train_loss = train(train_data, model, optimizer, epoch)
  File "train_ShuffleNetV2.py", line 145, in train
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
    for i, (img, heatmap_target, heat_mask, paf_target, paf_mask) in enumerate(train_loader):
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp, line 4044
    raise batch.exc_type(batch.exc_msg)
cv2.error: Traceback (most recent call last):
  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/wangmeng/pytorch_Realtime_Multi-Person_Pose_Estimation/training/datasets/coco_data/COCO_data_pipeline.py", line 238, in __getitem__
    meta_data, img, mask_miss, self.params_transform)
  File "/home/wangmeng/pytorch_Realtime_Multi-Person_Pose_Estimation/training/datasets/coco_data/ImageAugmentation.py", line 39, in aug_scale
    interpolation=cv2.INTER_CUBIC)
cv2.error: OpenCV(3.4.1) /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/imgproc/src/resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

**Comment by tensorboy** [comment]
Could you please check if the file path is correct.
