### ISSUE TITLE
getting some syntax error running on OS X

### ISSUE THREAD

**Issue by Sugarbank** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#5]
Christians-iMac:pytorch_Realtime_Multi-Person_Pose_Estimation-master sugarbank$ python picture_demo.py
  File "picture_demo.py", line 162
    print 'time is %.5f'%(toc-tic)

**Comment by Sugarbank** [comment]
Christians-iMac:pytorch_Realtime_Multi-Person_Pose_Estimation-master sugarbank$ python web_demo.py
  File "web_demo.py", line 154
    print oriImg.shape
               ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by tensorboy** [comment]
It is maybe a python version problem. ;-D.

**Comment by Sugarbank** [comment]
ah which version should i be running?

**Comment by Sugarbank** [comment]
Hi what version of python should I be running?Thanks

**Comment by tensorboy** [comment]
2.7 should be OK.

**Comment by Sugarbank** [comment]
got it working now thanks:)
