### ISSUE TITLE
From-scratch-model error

### ISSUE THREAD

**Issue by weihaosky** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#54]
Hi, I change the model used in picture_demo.py to your "pose_model_scratch.pth" but it gives me error "RuntimeError: Error(s) in loading state_dict for rtpose_model:
	Missing key(s) in state_dict: "model0.0.bias", ..........."
Did I miss something? The model "pose_model.pth" works well. Thank you.

**Comment by tensorboy** [comment]
Hi, @weihaosky . the model trained by multi-gpu has an extra `module` of the saved state dict. :) You may figure out it by adding a line `model = nn.DataParallel` or something else you can find to solve it.

**Comment by weihaosky** [comment]
Ok, get it. Thank you a lot.

**Comment by qiuzhongwei-USTB** [comment]
@weihaosky hi, I try to run this picture demo. And I meet this problem, could you be kind to tell me how did you fix it? where did you add "model = nn.DataParallel" in?

**Comment by weihaosky** [comment]
In short, the parameters name of the original model and the "pose_model_scratch" are different because "pose_model_scratch" uses DataParallel. You need to create a Parallel model  rather than the original model before you load the parameters of "pose_model_scratch". So after you create a model you need to convert the model to DataParaller model before you load the parameters.

**Comment by callmeB** [comment]
tl,dr:
just invert those two lines

https://github.com/tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation/blob/681d16fa6eac64d8828affa477af78dd358381d2/demo/picture_demo.py#L30-L31

**Comment by qiuzhongwei-USTB** [comment]
@callmeB hi, I add these two lines, just like the follows. but it doesn't work. 
![image](https://user-images.githubusercontent.com/34059431/45460748-054d4d00-b732-11e8-9950-54ac8c6c8290.png)

**Comment by tensorboy** [comment]
Inverse line 3 and 4
