### ISSUE TITLE
Crash in 'python convert.py'

### ISSUE THREAD

**Issue by wangxiaobupt** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#6]
model6_2.6.bias
model6_2.8.weight
model6_2.8.bias
model6_2.10.weight
model6_2.10.bias
model6_2.12.weight
model6_2.12.bias
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x7fc0c689ed90
[1]    969 abort      python convert.py

**Comment by tensorboy** [comment]
Did you fix it?
