### ISSUE TITLE
import config_reader from config_reader

### ISSUE THREAD

**Issue by pytorchfb** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#60]
After running the web_demo file  it says  "cannot import name 'config_reader'". I know its there in folder named caffe_to_pytorch but why its not importing it.

**Comment by pytorchfb** [comment]
Also what does this error mean?

AttributeError                            Traceback (most recent call last)
<ipython-input-46-d3f3c0aec1b0> in <module>()
     25 
     26 weight_name = './network/weight/pose_model.pth'
---> 27 model = get_model('vgg19')
     28 model.load_state_dict(torch.load(weight_name))
     29 model.cuda()

<ipython-input-21-e29fcc99db39> in get_model(trunk)
    220             init.normal_(self.model6_2[12].weight, std=0.01)
    221 
--> 222     model = rtpose_model(models)
    223     return model
    224 

<ipython-input-21-e29fcc99db39> in __init__(self, model_dict)
    152             self.model6_2 = model_dict['block6_2']
    153 
--> 154             self._initialize_weights_norm()
    155 
    156         def forward(self, x):

<ipython-input-21-e29fcc99db39> in _initialize_weights_norm(self)
    200             for m in self.modules():
    201                 if isinstance(m, nn.Conv2d):
--> 202                     init.normal_(m.weight, std=0.01)
    203                     if m.bias is not None:  # mobilenet conv2d doesn't add bias
    204                         init.constant_(m.bias, 0.0)

AttributeError: module 'torch.nn.init' has no attribute 'normal_'

**Comment by tensorboy** [comment]
It is a problem related to the pytorch version.
