### ISSUE TITLE
Cannot initialize CUDA without ATen_cuda library

### ISSUE THREAD

**Issue by shreya800** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#62]
hi, I am running web_demo.py on windows 10 without GPU. I got the following error message.

even if I run it by removing .cuda() in line 136 of coco_eval.py  I get the same error message.

RuntimeError                              Traceback (most recent call last)
<ipython-input-29-c272059082a2> in <module>()
     51         with torch.no_grad():
     52             paf, heatmap = get_outputs(
---> 53                 multiplier, oriImg, model,  'rtpose')
     54 
     55 

C:\Users\shreya.l.singh\Downloads\pytorch_Realtime_Multi-Person_Pose_Estimation-master\pytorch_Realtime_Multi-Person_Pose_Estimation-master\demo\coco_eval.py in get_outputs(multiplier, img, model, preprocess)
    134 
    135     # several scales as a batch
--> 136     batch_var = torch.from_numpy(batch_images).cuda().float()
    137     predicted_outputs, _ = model(batch_var)
    138     output1, output2 = predicted_outputs[-2], predicted_outputs[-1]

RuntimeError: Cannot initialize CUDA without ATen_cuda library. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason.  The CUDA library MUST be loaded, EVEN IF you don't directly use any symbols from the CUDA library! One common culprit is a lack of -Wl,--no-as-needed in your link arguments; many dynamic linkers will delete dynamic library dependencies if you don't depend on any of their symbols.  You can check if this has occurred by using ldd on your binary to see if there is a dependency on *_cuda.so library.

**Comment by pytorchfb** [comment]
Can I run web_demo.py on CPU? If yes, then what changes do I need to make in the code?

**Comment by tensorboy** [comment]
remove ’model.cuda()’ and ’images.cuda()’
