### ISSUE TITLE
 The download mask.tar.gz  is not match code.

### ISSUE THREAD

**Issue by janicevidal** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#68]
ori -- 'mask2014/val2014_mask_miss_' + img_idx + 'png'
download -- 'mask2014/val2014/mask_COCO_val2014_' + img_idx + 'jpg'

and there are lost images, like 'mask2014/train2014/mask_COCO_train2014_000000350444.jpg'

**Comment by TreB1eN** [comment]
so how to solve this issue ?

**Comment by janicevidal** [comment]
> so how to solve this issu
see https://github.com/CVBox/PyTorchCV
