### ISSUE TITLE
Resource Requirements

### ISSUE THREAD

**Issue by lauleehong** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#7]
How much hardware resources will we be requiring to run the picture/web demo? I'm attempting to run them on the JetsonTX1 (running at max turbo mode) but it could be a very far stretch as the output I get from the terminal for the picture demo is
`time is 0.68739`
`Killed`
indicating perhaps I have crossed the maximum resource threshold. Slight probing showed it crashed when running `output1,output2 = model(feed)`

**Comment by tensorboy** [comment]
Hi, @lauleehong . 

It is better with a very high-end GPU to do inference.

Best,
