### ISSUE TITLE
The trainning process

### ISSUE THREAD

**Issue by YixiaoZhang** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#75]
Hi,
What the train_ShuffleNetV2.py and train_VGG19.py use for?

Thank you!

**Comment by YixiaoZhang** [comment]
I got best_pose_SH.pth, best_pose_ShuffleNetV2.pth and vgg19-dcbb9e9d.pth. How to make it to a model which can be use for picture_demo?

**Comment by GreenTeaHua** [comment]
they all doesn't work for me,
they all need
  val2014_mask_miss_000000502629.png, ,,,,
but, bothing
