### ISSUE TITLE
how to detect person by using  bounding box  

### ISSUE THREAD

**Issue by Phoebe-star** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#8]
it just  like this  page 8
 http://image-net.org/challenges/talks/2016/Multi-person%20pose%20estimation-CMU.pdf

![image](https://user-images.githubusercontent.com/29423761/27121240-098650cc-5119-11e7-9892-8b63bbb91746.png)

**Comment by tensorboy** [comment]
SSD?

**Comment by Phoebe-star** [comment]
no, I don't have a ideal to know the code  that shows bounding message  (x,y,w,h).
